    -- while(b < 3)
    -- do
    --     repeat         
    --         c = c + 1
    --         print("C(",a,",",b,",",c,")")
    --     until(c > 2)
    --     b = b + 1
    --     print("B(",a,",",b,",",c,")")
    -- end